app:
  name: "GPT4Free API"
  version: "1.0.0"
  debug: false

server:
  host: "0.0.0.0"
  port: 8000
  workers: 4

rate_limit:
  requests_per_minute: 60
  burst_size: 100

cache:
  enabled: true
  ttl: 3600
  max_size: 1000

queue:
  max_size: 1000
  workers: 5

security:
  secret_key: "${SECRET_KEY}"
  allowed_hosts: ["*"]
  cors_origins: ["*"]

monitoring:
  enabled: true
  prometheus: true
  logging:
    level: "INFO"
    file: "logs/app.log"
